baseurl: ""
url: "http://localhost:3000/"
source: src/
destination: src/_site/
keep_files:
  - src/_site/.gitignore
  - src/_site/css
  - src/_site/images
  - src/_site/js
exclude:
  - .babelrc
  - .editorconfig
  - .gitignore
  - gulpfile.babel.js
  - package.json
  - readme.md
  - node_modules/
  - src/images/
  - src/scripts/
  - src/js/
